version: "3.1"

volumes:
  db-data:

services:
  web:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./app/:/app
    ports:
      - 8080:80
    environment:
      - DB_DSN=pgsql:host=db;port=5432;dbname=app
      - DB_USER=user_not_fit_for_prod
      - DB_PASS=password_not_fit_for_prod

  composer:
    image: composer
    working_dir: /app
    volumes:
      - ./app/:/app

  db:
    image: postgres
    ports: # Needed for dev purposes only
      - "5432:5432"
    volumes:  # Persist the db data
      - db-data:/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user_not_fit_for_prod
      - POSTGRES_PASSWORD=password_not_fit_for_prod

