version: "3.1"

volumes:
  db-data:

services:
  web:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./app/:/app
    ports:
      - 8080:80

  composer:
    image: composer
    working_dir: /app
    volumes:
      - ./app/:/app

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:  # Persist the db data
      - db-data:/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user_not_fit_for_prod
      - POSTGRES_PASSWORD=password_not_fit_for_prod

