<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UMS - <?= $this->title ?></title>
</head>

<body>
    <?= $this->parseTemplate($this->template); ?>
    <nav>
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/register">Register</a></li>
        </ul>
    </nav>
</body>
</html>
